language: java

jdk:
  - oraclejdk8
  #- openjdk9
  # https://github.com/travis-ci/travis-ci/issues/8975
  #- oraclejdk9

before_install:
  #  - sudo apt-get install gradle -y
  #  - sudo add-apt-repository ppa:cwchien/gradle -y
  #  - sudo apt-get update -q
  #  - sudo apt upgrade gradle -y

script:  
  - python --version
  - python build/create_problems_list.py