language: java

jdk:
  - oraclejdk9

before_install:
  - sudo apt-get install gradle
  - sudo add-apt-repository ppa:cwchien/gradle
  - sudo apt-get update -q
  - sudo apt upgrade gradle
  #- openjdk9

script:  
  - python --version
  - python build/create_problems_list.py