language: java

jdk:
  - oraclejdk8
  #- openjdk9
  # https://github.com/travis-ci/travis-ci/issues/8975
  #- oraclejdk9

before_install:
- sudo apt-get update -y
- sudo apt-get install python3 -y

script:
  - gradle test
  - python --version
  - python build/create_problems_list.py