language: java

jdk:
  - oraclejdk8
  #- openjdk9
  # https://github.com/travis-ci/travis-ci/issues/8975
  #- oraclejdk9

script:
  - gradle test
  - python3 --version
  - python3 build/create_problems_list.py