language: java

jdk:
  - oraclejdk8
  #- openjdk9
  # https://github.com/travis-ci/travis-ci/issues/8975
  #- oraclejdk9

before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
  - sudo apt-get update -y
  - sudo apt-get install python3.6 libpython3.6 -y

script:
  - gradle test
  - python3.6 --version
  - pip install markdown
  - pip install BeautifulSoup4
  - python3.6 build/create_problems_list.py

#https://caveofcode.com/2017/05/publish-an-angular-app-to-github-pages/