language: java

jdk:
  - oraclejdk8
  #- openjdk9
  # https://github.com/travis-ci/travis-ci/issues/8975
  #- oraclejdk9

python:
  - "3.6"

script:
  - gradle test
  - python --version
  - python build/create_problems_list.py