version: 1.0.{build}

branches:
  except:
  - gh-pages

skip_tags: true

image: Visual Studio 2017

environment:
  PYTHON: "C:\\Python36-x64"
  JDK9: "C:\\Program Files\\Java\\jdk9"

install:
  - cmd: choco install gradle
  - cmd: "SET JAVA_HOME=C:\\Program Files\\Java\\jdk9"
  - cmd: "SET python3=C:\\Python36-x64"
  - cmd: java -version
  - cmd: python3 --version"

build_script:
  - cmd: gradle build

after_build:
  - cmd: gradle test
  - cmd: python3 build\\run_unit_tests.py
  - cmd: python3 build\\create_problems_list.py

cache:
  - C:\Users\appveyor\.gradle