version: 1.0.{build}

branches:
  except:
  - gh-pages

skip_tags: true

image: Visual Studio 2017

environment:
  PYTHON: "C:\\Python36-x64"
  JDK9: "C:\\Program Files\\Java\\jdk9"

install:
  - cmd: choco install gradle
  - cmd: gradle -version
  # https://github.com/appveyor/ci/issues/1745
  - cmd: "set path=C:\\ProgramData\\chocolatey\\lib\\gradle\\tools\\gradle-4.5\\bin;%path%"
  - cmd: "SET JAVA_HOME=C:\\Program Files\\Java\\jdk9"
  - cmd: "SET PATH=%JAVA_HOME%\\bin;%path%"
  - cmd: "SET PYTHON3=C:\\Python36-x64"
  - cmd: "SET PATH=%PYTHON3%;%path%"
  - cmd: java -version
  - cmd: python --version"

build_script:
  - cmd: gradle build

after_build:
  - cmd: gradle test
  - cmd: python build\\run_unit_tests.py
  - cmd: python build\\create_problems_list.py

cache:
  - C:\Users\appveyor\.gradle