# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build_test_java:
    environment:
      CC_TEST_REPORTER_ID: CC_TEST_REPORTER_ID

    docker:
      # specify the version you desire here
      - image: circleci/openjdk:9-jdk-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - run:
        name: Setup dependencies
        command: |
          sudo composer self-update
          composer install -n --prefer-dist
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      - ./cc-test-reporter before-build
      # run tests!
      - run: gradle test   
      
      - run:
        name: Run tests for CodeClimate
          command: |
            sudo docker-php-ext-enable xdebug
            ./cc-test-reporter before-build
            sudo vendor/bin/phpunit --coverage-clover clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

  build_test_python:
    environment:
      CC_TEST_REPORTER_ID: CC_TEST_REPORTER_ID

    docker:      
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
        name: Setup dependencies
        command: |
          sudo composer self-update
          composer install -n --prefer-dist
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install markdown
            pip install BeautifulSoup4
            python3 build/create_problems_list.py
            # python3 build/run_unit_tests.py

      - run:
        name: Run tests for CodeClimate
          command: |
            sudo docker-php-ext-enable xdebug
            ./cc-test-reporter before-build
            sudo vendor/bin/phpunit --coverage-clover clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

workflows:
  version: 2
  build-test:
    jobs:
      - build_test_java:
          filters:
            branches:
              only:
                - master
      - build_test_python:        
          filters:
            branches:
              only:
                - master
          requires:
            - build_test_java